const ProfileActionTypes = {
  CREATE_PROFILE_START: 'CREATE_PROFILE_START',
  CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAILURE: 'CREATE_PROFILE_FAILURE',

  EDIT_PROFILE_START: 'EDIT_PROFILE_START',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',

  FETCH_PROFILE_START: 'FETCH_PROFILE_START',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

  FETCH_PROFILES_START: 'FETCH_PROFILES_START',
  FETCH_PROFILES_SUCCESS: 'FETCH_PROFILES_SUCCESS',
  FETCH_PROFILES_FAILURE: 'FETCH_PROFILES_FAILURE',

  CLEAR_PROFILE: 'CLEAR_PROFILE'
};

export default ProfileActionTypes;
