const ExperienceActionTypes = {
  FETCH_EXPERIENCES_START: 'FETCH_EXPERIENCES_START',
  FETCH_EXPERIENCES_SUCCESS: 'FETCH_EXPERIENCES_SUCCESS',
  FETCH_EXPERIENCES_FAILURE: 'FETCH_EXPERIENCES_FAILURE',

  ADD_EXPERIENCE_START: 'ADD_EXPERIENCE_START',
  ADD_EXPERIENCE_SUCCESS: 'ADD_EXPERIENCE_SUCCESS',
  ADD_EXPERIENCE_FAILURE: 'ADD_EXPERIENCE_FAILURE',

  DELETE_EXPERIENCE_START: 'DELETE_EXPERIENCE_START',
  DELETE_EXPERIENCE_SUCCESS: 'DELETE_EXPERIENCE_SUCCESS',
  DELETE_EXPERIENCE_FAILURE: 'DELETE_EXPERIENCE_FAILURE',

  CLEAR_EXPERIENCES: 'CLEAR_EXPERIENCES'
};

export default ExperienceActionTypes;
