const EducationActionTypes = {
  FETCH_EDUCATIONS_START: 'FETCH_EDUCATIONS_START',
  FETCH_EDUCATIONS_SUCCESS: 'FETCH_EDUCATIONS_SUCCESS',
  FETCH_EDUCATIONS_FAILURE: 'FETCH_EDUCATIONS_FAILURE',

  ADD_EDUCATION_START: 'ADD_EDUCATION_START',
  ADD_EDUCATION_SUCCESS: 'ADD_EDUCATION_SUCCESS',
  ADD_EDUCATION_FAILURE: 'ADD_EDUCATION_FAILURE',

  DELETE_EDUCATION_START: 'DELETE_EDUCATION_START',
  DELETE_EDUCATION_SUCCESS: 'DELETE_EDUCATION_SUCCESS',
  DELETE_EDUCATION_FAILURE: 'DELETE_EDUCATION_FAILURE',

  CLEAR_EDUCATIONS: 'CLEAR_EDUCATIONS'
};

export default EducationActionTypes;
